title = "El Blog de Adriel"
languageCode = "es-PE"
contentDir = "content"
languageName = "Español"
weight = 1

[params]
description = "Reflexiones, meditaciones, inquisiciones y disquisiciones sobre existir."
copyright = "Derechos reservados: Adriel Olórtegui Yzú - 2026"
displayName = "ES"
isoCode = "es"
dateFormat = "2 Enero del 2006"

[params.author]
name = "Adriel Olórtegui Yzú"
email = "blank"
headline = ""
links = [
	{ email = "adrielolorteguiyzu@gmail.com" },
]
