[[mounts]]
    source = "assets"
    target = "assets"
[[mounts]]
    source = "static"
    target = "static"
[[mounts]]
    source = "layouts"
    target = "layouts"
[[mounts]]
    source = "content"
    target = "content"
[[mounts]]
    source = "data"
    target = "data"

[hugo]
  [hugo.module]
    [[hugo.module.imports]]
      path = "github.com/nunocoracao/blowfish/v2"