replyByEmail = false

[article]
showAuthor = true
sharingLinks = [ ]
showTaxonomies = true
showCategories = true
showTags = true

[footer]
showAppearanceSwitcher = true

[homepage]
showRecent = true
cardView = true
cardViewScreenWidth = true
layout = "hero"
homepageImage = "camino_futuro.png"
showMoreLink = true
showMoreLinkDest = "showMoreLinkDest"
disableHeroImageFilter = true
