media:
  input: static/images
  output: /images
content:
  - name: posts
    label: 🖋️ Mis Publicaciones
    type: collection
    path: content/posts
    exclude: ["_index.md"]
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
