baseURL = 'https://aroy1962.xyz/'
languageCode = 'es-PE'
title = 'AROY1962'
theme = 'blowfish'

[params]
  description = 'Reflexiones - Disquisiciones - Inquisiciones'
  # Esto ayuda a que el diseño no se rompa
  mainSections = ["posts", "lecturas", "escritos_creativos", "resenas"]

[params.author]
  name = "El Blog de Adriel"
  # En el autor, el headline suele ser una sola línea corta
  # headline = "Medicina, Letras y Sentido"
  # image = "images/Hojanaranja.png"

[params.homepage]
  layout = "background"
  image = "images/Hojanaranja.png"
  imageSize = "cover"
  showHerald = false
  title = "AROY1962"
  tagline = """
  Sobre el transcurrir de los días...  \n y la búsqueda de sentido en las letras.
  """ # 👈 Tus dos líneas con el salto
  showNews = true # Para que tus artículos aparezcan debajo del encabezado

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Principio"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "creacion"
    name = "Creación"
    url = "/lecturas/"
    weight = 20
  [[menu.main]]
    identifier = "escritos"
    name = "Ensayando"
    url = "/escritos_creativos/"
    weight = 30
  [[menu.main]]
    identifier = "resena"
    name = "Reseñas"
    url = "/resenas/"
    weight = 40
[[menu.main]]
    identifier = "acerca"
    name = "Acerca de"
    url = "/posts/"
    weight = 50

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true

[outputs]
  home = ["HTML", "RSS", "JSON"]