baseURL = 'https://aroy1962.xyz/'
languageCode = 'es-PE'
title = 'AROY1962'
theme = 'blowfish'

[params]
  description = 'Reflexiones - Disquisiciones - Inquisiciones'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  stickyHeader = false

[params.author]
  headline = 'Sobre el transcurrir'
  bio = 'Reflexiones - Disquisiciones - Inquisiciones'
  # image = 'images/tu-foto.jpg' # Opcional: coloca una foto en static/images/

[params.assets]
  disableHLJS = false
  disableFingerprinting = false  # ← CRÍTICO

[params.homeInfoParams]
  Title = "AROY1962"
  Content = "Blog Adriel Olórtegui Yzú"

  [[menu.main]]
    identifier = "inicio"
    name = "Principio"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "creacion"
    name = "Creación"
    url = "/lecturas/"
    weight = 20
  [[menu.main]]
    identifier = "escritos"
    name = "Ensayando"
    url = "/escritos_creativos/"
    weight = 30
  [[menu.main]]
    identifier = "resena"
    name = "Reseñas"
    url = "/resenas/"
    weight = 40
  [[menu.main]]
    identifier = "acerca"
    name = "Acerca de"
    url = "/posts/"
    weight = 50

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.profileMode]
    enabled = true
    title = "AROY1962: Medicina, Letras y Sentido"
    subtitle = "Explorando la intersección entre el arte de curar y el oficio de escribir."
    imageUrl = "images/tu-banner-hero.jpg" # Ubicada en static/images/
    imageWidth = 150
    imageHeight = 150
    imageTitle = "Logo AROY1962"
    
    [[params.profileMode.buttons]]
        name = "📖 Empezar a leer"
        url = "posts/"
    [[params.profileMode.buttons]]
        name = "✍️ Sobre mí"
        url = "about/"