baseURL = 'https://aroy1962.xyz/'
languageCode = 'es-PE'
title = 'Inquisiciones'
theme = 'PaperMod'

[params]
  author = 'Dr. Adriel Olórtegui Yzú'
  description = 'Reflexiones sobre la condición humana en tiempos de deshumanización.'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  additionalCSS = ["/css/inquisiciones.css"]

[params.homeInfoParams]
  Title = "Inquisiciones"
  Content = "Reflexiones sobre la condición humana en tiempos de deshumanización."

[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "Inicio"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "lecturas"
    name = "Lecturas"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "acerca"
    name = "Acerca de"
    url = "/acerca/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
